-- JOIN
-- GROUP BY절 -> 어떤 컬럼으로 그루핑을 할지 잘 생각
SELECT
    II.INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF FH
    JOIN
    ICECREAM_INFO II
    ON
    FH.FLAVOR = II.FLAVOR    
GROUP BY
    II.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER
    ASC
