-- HOUR()
-- GROUP BY
-- GROUP BY, ORDER BY 절에서 Alias 명으로도 가능
SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(DATETIME) AS COUNT
FROM
    ANIMAL_OUTS
WHERE
    HOUR(DATETIME) >= 9
    AND
    HOUR(DATETIME) < 20
GROUP BY
    HOUR
ORDER BY
    HOUR
