-- 총매출 = ((SUM(AMOUNT) * PRICE))
-- GROUP BY
-- JOIN
SELECT
    FP.PRODUCT_ID AS PRODUCT_ID
    , FP.PRODUCT_NAME AS PRODUCT_NAME
    , (SUM(FO.AMOUNT) * FP.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT FP
    JOIN
    FOOD_ORDER FO
    ON
    FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE
    FO.PRODUCE_DATE
    LIKE
    '2022-05%'
GROUP BY
    FP.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC
