-- DISTINCT
-- JOIN
-- WHERE + AND
SELECT
    DISTINCT CH.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    JOIN
    CAR_RENTAL_COMPANY_CAR CC
    ON CH.CAR_ID = CC.CAR_ID
WHERE
    CC.CAR_TYPE = '세단'
    AND
    CH.START_DATE
        LIKE
        '%-10-%'
ORDER BY
    CH.CAR_ID
    DESC
