-- LEFT OUTER JOIN의 왼쪽에 어떤 테이블을 둘지 판단
SELECT
    AO.ANIMAL_ID AS ANIMAL_ID
    , AO.NAME AS NAME
FROM
    ANIMAL_OUTS AO
    LEFT OUTER JOIN
    ANIMAL_INS AI
        ON
        AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE
    AI.ANIMAL_ID IS NULL
ORDER BY
    AO.ANIMAL_ID
    ASC
