-- INNER JOIN
-- DATEDIFF()도 ORDER BY절에 들어갈 수 있음
-- LIMIT
SELECT
    AI.ANIMAL_ID AS ANIMAL_ID
    , AI.NAME AS NAME
FROM
    ANIMAL_INS AI
    JOIN
    ANIMAL_OUTS AO
        ON
        AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY
    DATEDIFF(AO.DATETIME, AI.DATETIME)
    DESC
LIMIT 2
